Feature/word list
Ita-Donosoft/nelliezabel pull request #1
Opened 2022-12-06 02:35 UTC by JimmyCamus

# List of words
## Description
In this feature the word list is added, which shows the word itself and the category. Also pagination is added with a maximum of 30 words per page.
### Features
1. List of words
2. Function to obtain words from firebase
3. Pagination (30 words per page)
### Results
#### Desktop
![image](https://user-images.githubusercontent.com/86853554/205794214-72eb524d-df25-4fb7-9810-9b12cba11a61.png)

#### Mobile
![image](https://user-images.githubusercontent.com/86853554/205794284-d17f3a9e-2479-4355-83ab-7eed4fc83016.png)

2022-12-06 23:42 UTC, Jimeneznet requested changes
Casi todo bien, solo el detalle mencionado en el comentario.
-> Por favor recordarme después de agregar los colores al tema del tailwind
-> No testeado en esta revisión de código

2022-12-06 23:42 UTC, Jimeneznet commented on src/components/dictionary/DictionaryRow.tsx
> +    }
Cambiar por switch case, o parametrizar con una enumeración o diccionario.

2022-12-07 00:32 UTC, JimmyCamus commented on src/components/dictionary/DictionaryRow.tsx
> +    }
Se realizó un cambio a un switch y se añadió un enum con los posibles valores de las categorías definidas en el ERS.

2022-12-07 00:52 UTC, Jimeneznet approved these changes
Nice

2022-12-07 01:17 UTC, merged